image: mcr.microsoft.com/playwright:focal

stages:
  - test

variables:
  # Set any environment variables here
  NODE_ENV: test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - ms-playwright/ # Change to a relative path to avoid warnings

test_playwright:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - yarn playwright test --reporter=dot,junit
  timeout: 2h # Increases the timeout to 2 hours
  artifacts:
    when: always
    paths:
      - test_results.xml # JUnit report is saved in the root
      - playwright-report/ # Playwright HTML report is saved here
    reports:
      junit: test_results.xml
  only:
    - branches
